name: Python Tests

on:
  push:
    branches:
      - main  # Workflow sẽ chạy khi có thay đổi trên nhánh main
  pull_request:
    branches:
      - main  # Workflow sẽ chạy khi có pull request vào nhánh main

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy workflow trên môi trường Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Lấy mã nguồn từ repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Cài đặt Python 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Cài đặt các phụ thuộc từ tệp requirements.txt

      - name: Run flake8
        run: |
          flake8 .  # Kiểm tra mã nguồn với flake8

      - name: Run tests
        run: |
          pytest  # Chạy pytest để kiểm tra mã nguồn

      - name: Send Telegram Notification on Failure
        if: failure()  # Chỉ gửi thông báo nếu kiểm thử thất bại
        uses: appleboy/telegram-action@v0.0.8
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: 'Tests failed in GitHub Actions for your project!'
